### ISSUE TITLE
High cpu usages

### ISSUE THREAD

**Issue by xs404** [blenderskool/blaze#106]
Scene was transfer between my two chromium browsers.

**Comment by blenderskool** [comment]
Would require more testing on what is causing high CPU usages. Two places that I can note:
- WebTorrent and WebRTC communications might be intensive in which case we probably can't do anything about it.
- Intensive canvas updates for the loading indicator.

**Comment by blenderskool** [comment]
Closing this, as there were no additional details provided like file size, chromium versions, etc.

I suspect the high CPU usage to be because of a large file being transferred by WebTorrent. Can't do much about it. If someone finds additional details and possible solutions, we can open this issue and discuss it again.
