### ISSUE TITLE
Selecting and sending multiple files from Android doesn't work.

### ISSUE THREAD

**Issue by Irfan-S** [blenderskool/blaze#50]
Issue sending multiple files between Android and Linux on Firefox. Operation ends up stalling.
 
Firefox on Linux shows an active WebSocket connection, whereas Android shows WebRTC.

On batch select and send from Android , the files seem to get overlapped, which result in no transmission.

**Comment by blenderskool** [comment]
I can't seem to replicate this issue. Can you share additional info such as
- Browser on Android
- Number of files shared

**Comment by Irfan-S** [comment]
Firefox on Android to Firefox on Linux
Files shared : 5

![7D2F7274-AD57-486E-B81E-22D11161499B](https://user-images.githubusercontent.com/31773650/69933636-61e28680-14f5-11ea-8a82-23fe60c6a77d.png)
This is another test from Firefox on Android to Firefox on iOS 
The first file, with size 0kB, Is a selection of 5 images. Does not get transferred.
Further transfers between devices on Firefox do not seem to work.(Tested between iPad and Android , Android and Laptop)

**Comment by blenderskool** [comment]
@Irfan-S This issue is more geared towards Firefox mobile. On checking [caniuse](https://caniuse.com/#feat=input-file-multiple), I find that Firefox for Android **does not support multiple file selection**. I assume same issue with Firefox on iOS as well.

Having said that, our best bet may be to not allow invalid multiple file selection on Firefox mobile, similar to how other tools like Firefox Send handle this.

**Comment by Irfan-S** [comment]
Awesome! Works great now. Really neat tool
